# Generated by Django 4.2.3 on 2023-08-16 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clases',
            new_name='Clases1',
        ),
    ]
