# Generated by Django 4.2.3 on 2023-08-16 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_rename_clases_clases1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clases1',
            new_name='Clases',
        ),
    ]
